from page.Factory_Bot import show_factorybot
from page.Factory_Astro import Show_Factoryastro
from page.Predictive_Performance import show_PredictivePerformance
from page.Startup import show_image
from page.all_metrics import show_allmetrics
from page.churn_prediction import show_churn_pred